# Generated by Django 4.2.16 on 2024-11-11 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_course', models.CharField(max_length=350, verbose_name='Название курса')),
                ('description_course', models.TextField(blank=True, null=True, verbose_name='Описание курса')),
                ('image_course', models.ImageField(blank=True, null=True, upload_to='image_course/', verbose_name='Превью курса')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_lesson', models.CharField(max_length=350, verbose_name='Название урока')),
                ('description_lesson', models.TextField(blank=True, null=True, verbose_name='Описание урока')),
                ('image_lesson', models.ImageField(blank=True, null=True, upload_to='image_lesson/', verbose_name='Превью урока')),
                ('link_video', models.URLField(blank=True, max_length=550, null=True, verbose_name='Ссылка на видео')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='materials.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['-id'],
            },
        ),
    ]
