# Generated by Django 4.2.16 on 2024-11-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=550, verbose_name='Вариант ответа')),
                ('right_answer', models.BooleanField(default=False, verbose_name='Признак правильного ответа')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_answer', models.BooleanField(default=False, verbose_name='Ответ выбран верно')),
            ],
            options={
                'verbose_name': 'Выбранный ответ',
                'verbose_name_plural': 'Выбранные ответы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=550, verbose_name='Тестовый вопрос')),
            ],
            options={
                'verbose_name': 'Тестовое задание',
                'verbose_name_plural': 'Тестовые задания',
                'ordering': ['-id'],
            },
        ),
    ]
