# Generated by Django 4.2.16 on 2024-11-11 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['-id'], 'verbose_name': 'Проверка', 'verbose_name_plural': 'Проверка'},
        ),
    ]
