# Generated by Django 4.2.16 on 2024-11-13 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0004_alter_choice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['-id'], 'verbose_name': 'Проверка знаний', 'verbose_name_plural': 'Проверки знаний'},
        ),
    ]
