# Generated by Django 4.2.16 on 2024-11-13 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0005_alter_choice_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='checks.answer', verbose_name='Выбранный ответ'),
        ),
    ]
