# Generated by Django 4.2.16 on 2024-11-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0006_alter_choice_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='Курс'),
        ),
    ]
